title: Nigar (Leeza) Sultana # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Business Analyst with 3+ years of experience in using statistical and ML modeling to make data-driven strategies for businesses. Proficiently skilled in employing Python, R, STATA, SQL Query, and Tableau to extract actionable insights to facilitate informed business decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/nisultana/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
