title: Nigar Sultana # your name (or website title) here
logo: "IMG_2280.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 When it comes to data analysis and visualization, I find storytelling an excellent medium to present numbers.
 I believe every data set has a story to tell and insights to offer that can help us solve problems.
 Like literary stories, data storytelling requires crafting a clear beginning, thrilling twists in the middle, and an actionable happy ending. 
 Before communicating data through storytelling, knowing stakeholders' realistic goals and priorities help me analyze and filter down the most significant bits.
  <br><br>
  <a href="https://www.linkedin.com/in/nisultana/">View My LinkedIn Profile</a> 


 theme: jekyll-theme-minimal
   <br><br>
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
